SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    PURCHASING.QMDATE

FROM
    PURCHASING
    LEFT JOIN DATETABLE
        ON PURCHASING.QMDATE = DATETABLE.Date

GROUP BY
    DATETABLE.Year
    PURCHASING.QMDATE;
