SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    JRCP.QMDATE

FROM
    JRCP
    INNER JOIN DATETABLE
        ON JRCP.QMDATE = DATETABLE.Date

GROUP BY
    DATETABLE.Year
    JRCP.QMDATE;
