SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    PASAFETY.QMDATE

FROM
    DATETABLE
    INNER JOIN PASAFETY
        ON DATETABLE.Date = PASAFETY.QMDATE

GROUP BY
    DATETABLE.Year
    PASAFETY.QMDATE;
