SELECT
    DATETABLE.Month,
    DATETABLE.Year

FROM
    DATETABLE
    INNER JOIN HANDWASHING
        ON DATETABLE.Date = HANDWASHING.HWDATE

GROUP BY
    DATETABLE.Month
    DATETABLE.Year;
