SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    PSY.QMDATE

FROM
    PSY
    INNER JOIN DATETABLE
        ON PSY.QMDATE = DATETABLE.Date

GROUP BY
    DATETABLE.Year
    PSY.QMDATE;
