SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    FISCAL.QMDATE

FROM
    FISCAL
    INNER JOIN DATETABLE
        ON FISCAL.QMDATE = DATETABLE.Date

GROUP BY
    DATETABLE.Year
    FISCAL.QMDATE;
