SELECT
    DATETABLE.Month,
    DATETABLE.Year

FROM
    DATETABLE
    INNER JOIN [INCIDENT TRACKER]
        ON DATETABLE.Date = [INCIDENT TRACKER].Date

GROUP BY
    DATETABLE.Month
    DATETABLE.Year;
