SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    DIET.QMDATE

FROM
    DIET
    LEFT JOIN DATETABLE
        ON DIET.QMDATE = DATETABLE.Date

GROUP BY
    DATETABLE.Year
    DIET.QMDATE;
