SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    SDT.QMDATE

FROM
    SDT
    INNER JOIN DATETABLE
        ON SDT.QMDATE = DATETABLE.Date

GROUP BY
    DATETABLE.Year
    SDT.QMDATE;
