SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    GROUPS.QMDATE

FROM
    DATETABLE
    INNER JOIN GROUPS
        ON DATETABLE.Date = GROUPS.QMDATE

GROUP BY
    DATETABLE.Year
    GROUPS.QMDATE;
