SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    PHARM.QMDATE

FROM
    PHARM
    LEFT JOIN DATETABLE
        ON PHARM.QMDATE = DATETABLE.Date

GROUP BY
    DATETABLE.Year
    PHARM.QMDATE;
