SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    XRAY.QMDATE

FROM
    DATETABLE
    INNER JOIN XRAY
        ON DATETABLE.Date = XRAY.QMDATE

GROUP BY
    DATETABLE.Year
    XRAY.QMDATE;
