SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    COMMENTS.QMDATE

FROM
    COMMENTS
    INNER JOIN DATETABLE
        ON COMMENTS.QMDATE = DATETABLE.Date

GROUP BY
    DATETABLE.Year
    COMMENTS.QMDATE
    COMMENTS.DEPTID

HAVING
    (((COMMENTS.DEPTID)="021"));
