SELECT
First(DATETABLE.Month) AS FirstOfMonth,
    DATETABLE.Year,
    ADMIS.QMDATE

FROM
    ADMIS
    INNER JOIN DATETABLE
        ON ADMIS.QMDATE = DATETABLE.Date

GROUP BY
    DATETABLE.Year
    ADMIS.QMDATE;
