SELECT
    DEQDELINQUENCY.DEQKEY,
    DEQPATIENT.PatientID,
    DEQPATIENT.EPI,
    [LNAME] & ", " & [FNAME] & " " & [DEQPATIENT].[MI] & "." AS [Full Name],
    DEQDELINQUENCY.DID,
    DEQDELINQUENCY.DMID,
    DEQDELINQUENCY.DEQID,
    DEQDELINQUENCY.DEFID,
    DEQDELINQUENCY.EDATE,
    DEQDELINQUENCY.EMPID,
    IIf(
        [STATUS]="Resolved",
DateDiff("d",[EDATE],[RDATE]),
Val(([EDATE]-Date())*(-1))
    )AS [Days Deq Calq],
    UNIT.UNITSUB,
    UNIT.UNITMAIN,
    BUILDING.[BUILDING#],
    DEQRESOLUTION.RDATE,
    IIf(
IsNull([STATUS]),
        "Outstanding",
        "Resolved"
    )AS Reso,
    SATELLITE2.[SUPV#],
    [DEQDELINQUENCY].[PatientID] & "-" & [Episode] AS patepi,
    IIf(
        [Reso]="Resolved",
        "Resolved",
        [Days Deq Calq]
    )AS [Days Deq],
    SATELLITE2.EMPSTATUS,
    DEQDELINQUENCY.COMMENT,
    DEQRESOLUTION.STATUS,
    SATELLITE2.[Full Name] AS EmpFullName,
    DEQDELINQUENCY.Episode,
    DEQDELINQUENCY.Timestamp,
    DEQDELINQUENCY.Alias,
    DEQDELINQUENCY.PorE,
    DEQDEF.DEFDESC,
    DEQDISCIPLINE.DISCIPLINE,
    DEQMAINCATS.DEMAINDESC,
    DelinquencySubCats.SUBDEQNAME,
    PORE.PEDESC,
    [Alias-Usernames].[Full Name] AS [Auditor Name]

FROM
    (((((((DEQRESOLUTION RIGHT JOIN (BUILDING RIGHT JOIN (UNIT RIGHT JOIN (DEQPATIENT RIGHT JOIN DEQDELINQUENCY ON (DEQPATIENT.EPI = DEQDELINQUENCY.Episode) AND (DEQPATIENT.PatientID = DEQDELINQUENCY.PatientID)) ON UNIT.UNITSUB = DEQPATIENT.UNIT) ON BUILDING.BUI = UNIT.BUI) ON DEQRESOLUTION.DEQKEY = DEQDELINQUENCY.DEQKEY) LEFT JOIN SATELLITE2 ON DEQDELINQUENCY.EMPID = SATELLITE2.[EMP ID]) LEFT JOIN DEQDEF ON DEQDELINQUENCY.DEFID = DEQDEF.DEFKEY) LEFT JOIN DEQDISCIPLINE ON DEQDELINQUENCY.DID = DEQDISCIPLINE.DKEY) LEFT JOIN DEQMAINCATS ON DEQDELINQUENCY.DMID = DEQMAINCATS.DMKEY) LEFT JOIN DelinquencySubCats ON DEQDELINQUENCY.DEQID = DelinquencySubCats.DEQKEY) LEFT JOIN PORE ON DEQDELINQUENCY.PorE = PORE.PEID)
    LEFT JOIN [Alias-Usernames]
        ON DEQDELINQUENCY.Alias = [Alias-Usernames].Alias

WHERE
    (((DEQRESOLUTION.STATUS) Is Null Or (DEQRESOLUTION.STATUS)<>"Deleted"));
