SELECT
    DEQDELINQUENCY.PatientID,
Count(DEQDELINQUENCY.PatientID) AS CountOfPatientID

FROM
    DEQRESOLUTION
    RIGHT JOIN DEQDELINQUENCY
        ON DEQRESOLUTION.DEQKEY = DEQDELINQUENCY.DEQKEY

GROUP BY
    DEQDELINQUENCY.PatientID
    DEQRESOLUTION.STATUS

HAVING
    (((DEQRESOLUTION.STATUS) Is Null))

ORDER BY
    Count(DEQDELINQUENCY.PatientID) DESC;
