SELECT
    DEQDELINQUENCY.DEQKEY,
    DEQPATIENT.PatientID,
    DEQPATIENT.EPI,
    [LNAME] & ", " & [FNAME] & " " & [MI] & "." AS [Full Name],
    DEQDELINQUENCY.DID,
    DEQDELINQUENCY.DMID,
    DEQDELINQUENCY.DEQID,
    DEQDELINQUENCY.DEFID,
    DEQDELINQUENCY.EDATE,
    DEQDELINQUENCY.EMPID,
    ([EDATE]-Date())*(-1) AS [Days Deq],
    UNIT.UNITSUB,
    UNIT.UNITMAIN,
    BUILDING.[BUILDING#],
    DEQRESOLUTION.RDATE,
    IIf(
IsNull([STATUS]),
        "Outstanding",
        "Resolved"
    )AS Reso,
    [DEQDELINQUENCY].[PatientID] & "-" & [Episode] AS patepi,
    DEQDELINQUENCY.Alias,
    DEQDELINQUENCY.COMMENT,
    EmployeeIDandAlias.[Full Name] AS [Auditor Name],
    PORE.PEDESC

FROM
    (EmployeeIDandAlias RIGHT JOIN (DEQRESOLUTION RIGHT JOIN (BUILDING RIGHT JOIN (UNIT RIGHT JOIN (DEQPATIENT RIGHT JOIN DEQDELINQUENCY ON (DEQPATIENT.EPI = DEQDELINQUENCY.Episode) AND (DEQPATIENT.PatientID = DEQDELINQUENCY.PatientID)) ON UNIT.UNITSUB = DEQPATIENT.UNIT) ON BUILDING.BUI = UNIT.BUI) ON DEQRESOLUTION.DEQKEY = DEQDELINQUENCY.DEQKEY) ON EmployeeIDandAlias.Alias = DEQDELINQUENCY.Alias)
    LEFT JOIN PORE
        ON DEQDELINQUENCY.PorE = PORE.PEID

WHERE
    ((( IIf(
IsNull([STATUS]),
        "Outstanding",
        "Resolved"
    ) )<>"Resolved"));
