SELECT
    DEQPATIENT.PatientID,
    DEQPATIENT.EPI,
    [LNAME] & ", " & [FNAME] & " " & [MI] & "." AS [Full Name],
    BUILDING.[BUILDING#],
    UNIT.UNITMAIN,
    DEQPATIENT.UNIT,
    DEQPATIENT.ADMISDT,
    DEQPATIENT.DISDT,
    DEQPATIENT.FNAME,
    DEQPATIENT.LNAME,
    DEQPATIENT.MI,
    [PatientID] & "-" & [EPI] AS patepi

FROM
    (UNIT RIGHT JOIN DEQPATIENT ON UNIT.UNITSUB = DEQPATIENT.UNIT)
    LEFT JOIN BUILDING
        ON UNIT.BUI = BUILDING.BUI

ORDER BY
    DEQPATIENT.PatientID DESC
    DEQPATIENT.EPI DESC;
