SELECT
    DEQMAINCATS.DEMAINDESC,
    DEQSUBCATS.REQUIRED,
    DEQSUBCATS.SUBDEQNAME,
    DEQSUBCATS.STATUS,
    DEQSUBCATS.DEQTYPE

FROM
    DEQMAINCATS
    INNER JOIN DEQSUBCATS
        ON DEQMAINCATS.DMKEY = DEQSUBCATS.MAINDEQID;
