SELECT
    AFFILIATIONPROGRAM.[AGREE-NUM],
    AFFILIATIONSCHOOL.[SCH-NAME],
    AFFILIATIONPROGRAM.[PROG-NAME]

FROM
    AFFILIATIONPROGRAM
    INNER JOIN AFFILIATIONSCHOOL
        ON AFFILIATIONPROGRAM.[SCH-ID] = AFFILIATIONSCHOOL.[SCH-ID];
