SELECT
    AFFILIATIONPOC.POCID,
    [POCFNAME] & " " & [POCLNAME] AS [Full Name]

FROM
    AFFILIATIONPOC

GROUP BY
    AFFILIATIONPOC.POCID
    [POCFNAME] & " " & [POCLNAME]

HAVING
    (((AFFILIATIONPOC.POCID)<>0));
