SELECT
    SATELLITE2.[EMP ID],
    SATELLITE2.JOBTITLE,
    SATELLITE2.FIRSTNAME,
    SATELLITE2.LASTNAME,
    SATELLITE2.BIRTHDATE,
    SATELLITE2.EMPSTATUS,
Month([BIRTHDATE]) AS [Month],
Day([BIRTHDATE]) AS [Day],
    SATELLITE2.[Photo Path],
    SATELLITE2.[Full Name]

FROM
    SATELLITE2

WHERE
    (((SATELLITE2.EMPSTATUS)="Current") AND ((Month([BIRTHDATE]))=Month(Date())) AND ((Day([BIRTHDATE]))=Day(Date())))

ORDER BY
    SATELLITE2.BIRTHDATE DESC;
