SELECT
    LICENSESAT.EID,
    LICENSESAT.[LICENSE-NUMBER],
    ERLICENSE.[LICENSE DESCRIPTION],
    LICENSESAT.[LIC-EXPIRE-DATE],
    LICENSESAT.INITIALDATE,
    STATES.StateLOW

FROM
    (LICENSESAT LEFT JOIN STATES ON LICENSESAT.STATE = STATES.StateABR)
    LEFT JOIN ERLICENSE
        ON LICENSESAT.[TYPE-OF-LICENSE] = ERLICENSE.[LICENSE NUMBER];
