SELECT
    SATELLITE2.[EMP ID],
    SATELLITE2.[Full Name],
    SATELLITE2.JOBTITLE,
    SATELLITE2.[BLDG#],
    SATELLITE2.POD,
    SATELLITE2.WARD,
    SATELLITE2.[SUPV#]

FROM
    SATELLITE2

WHERE
    (((SATELLITE2.EMPSTATUS)="Separated"));
