SELECT
    SATELLITE2.[EMP ID],
    SATELLITE2.[Full Name],
    SATELLITE2.JOBTITLE,
    SATELLITE2.[BLDG#],
    SATELLITE2.POD,
    SATELLITE2.WARD,
    SATELLITE2.[SUPV#],
    SATELLITE2.[CC-BASE],
    SATELLITE2.[ROLE-CODE],
    SATELLITE2.NursingDesignationCode,
    ERCOSTCENTER.[CC-DESC],
    ERROLECODE.[ROLE-DESC],
    SupervisorInformationALL.[Supervisor Name],
    SupervisorInformationALL.JOBTITLE AS SupvJobTitle,
    SATELLITE2.[Photo Path],
    SATELLITE2.EMPSTATUS,
    SATELLITE2.SEPARATION,
    SATELLITE2.[POSTYP DESC],
    SATELLITE2.[ESH-HIRE-DATE],
    SATELLITE2.[POS-START-DATE],
    SATTEMPKEY.SSN

FROM
    (((SATELLITE2 LEFT JOIN ERCOSTCENTER ON SATELLITE2.[CC-BASE] = ERCOSTCENTER.[CC-BASE]) LEFT JOIN ERROLECODE ON SATELLITE2.[ROLE-CODE] = ERROLECODE.[ROLE-CODE]) LEFT JOIN SupervisorInformationALL ON SATELLITE2.[SUPV#] = SupervisorInformationALL.[SUPV#])
    LEFT JOIN SATTEMPKEY
        ON SATELLITE2.[EMP ID] = SATTEMPKEY.[EMP ID]

WHERE
    (((SATELLITE2.[EMP ID]) Is Not Null));
