SELECT
    SATELLITE2.[EMP ID],
    SATELLITE2.FIRSTNAME,
    SATELLITE2.LASTNAME,
    SATELLITE2.MI,
    SATELLITE2.JOBTITLE,
    SATELLITE2.[CC-DESC],
    SATELLITE2.[DUTY#],
    SATELLITE2.[POSTYP DESC],
    SATELLITE2.EMPSTATUS,
    SATELLITE2.SEPARATION

FROM
    SATELLITE2

WHERE
    (((SATELLITE2.EMPSTATUS)<>"Place Holder"));
