SELECT
    SATELLITE2.[EMP ID]

FROM
    SATELLITE2

GROUP BY
    SATELLITE2.[EMP ID]
    SATELLITE2.EMPSTATUS

HAVING
    (((SATELLITE2.EMPSTATUS)="separated" Or (SATELLITE2.EMPSTATUS)="current"));
