SELECT
    SATELLITE2.[EMP ID],
    SATELLITE2.FIRSTNAME,
    SATELLITE2.LASTNAME,
    SATELLITE2.MI,
    SATELLITE2.[CC-DESC],
    [EMP ID] & [Full Name] & [CC-DESC] AS Expr1

FROM
    SATELLITE2;
