SELECT
    FITTESTING.FITID,
    FITTESTING.FITKEY,
    FITTESTING.EMPID,
    FITTESTING.FTDATE,
    FITTRAINSTATUS.TRAINDESC,
    FITPPETYPES.MASKTYPE,
    FITBRANDS.BRANDDESC,
    FITTESTING.SIZE,
    FITTESTING.NOTES

FROM
    (FITTRAINSTATUS RIGHT JOIN (FITPPETYPES RIGHT JOIN FITTESTING ON FITPPETYPES.MASKKEY = FITTESTING.MASKTYPE) ON FITTRAINSTATUS.TRAINID = FITTESTING.TRAININGSTAT)
    LEFT JOIN FITBRANDS
        ON FITTESTING.BRAND = FITBRANDS.BRANDID;
