SELECT
    FitTestingLog.EMPID,
    SATELLITE2.[Full Name],
    FITBRANDS.BRANDDESC,
    FITPPETYPES.MASKTYPE,
    FITTRAINSTATUS.TRAINDESC,
    SATELLITE2.[BLDG#],
    SATELLITE2.POD,
    SATELLITE2.WARD,
    SATELLITE2.NursingDesignationCode,
    FitTestingMedApproval.APPROVAL,
    NONVSN.DESC

FROM
    NONVSN
    RIGHT JOIN (FitTestingMedApproval RIGHT JOIN (SATELLITE2 RIGHT JOIN (FITPPETYPES RIGHT JOIN (FITBRANDS RIGHT JOIN (FITTRAINSTATUS RIGHT JOIN FitTestingLog
        ON FITTRAINSTATUS.TRAINID = FitTestingLog.TRAININGSTAT) ON FITBRANDS.BRANDID = FitTestingLog.BRAND) ON FITPPETYPES.MASKKEY = FitTestingLog.MASKTYPE) ON SATELLITE2.[EMP ID] = FitTestingLog.EMPID) ON FitTestingMedApproval.EMPID = FitTestingLog.EMPID) ON NONVSN.NDCID = SATELLITE2.NursingDesignationCode

WHERE
    (((SATELLITE2.[BLDG#]) Is Not Null) AND ((SATELLITE2.SEPARATION) Is Null));
