SELECT
    FITTESTING.EMPID,
    FITTESTING.TRAININGSTAT,
    FITTESTING.MASKTYPE,
    FITTESTING.BRAND,
    FITTESTING.FTDATE,
    FITTESTING.NOTES,
    SATELLITE2.EMPSTATUS AS Separated,
    SATELLITE2.[BLDG#],
    SATELLITE2.POD,
    SATELLITE2.WARD,
    FITTESTING.FITID,
    FITTESTING.FITKEY,
    FITTESTING.SIZE

FROM
    SATELLITE2
    INNER JOIN FITTESTING
        ON SATELLITE2.[EMP ID] = FITTESTING.EMPID;
