SELECT
    N95APPRV.N95ID,
    N95APPRV.EMPID,
    SATELLITE2.[Full Name],
    N95APPRV.N95APPRV,
    N95APPRV.MEDSCREEN,
    N95APPRV.N95DATE,
    SATPOSITION.[SUPV#]

FROM
    (SATELLITE2 INNER JOIN N95APPRV ON SATELLITE2.[EMP ID] = N95APPRV.EMPID)
    INNER JOIN SATPOSITION
        ON SATELLITE2.[POSITION#] = SATPOSITION.[POSITION#]

ORDER BY
    SATPOSITION.[SUPV#] DESC;
