SELECT
    FITSCHEDULED.EMPID,
    FITSCHEDULED.TIMESLOT,
    FITSCHEDULED.Weekday,
    FITSCHEDULED.DATESLOT,
    SATPOSITION.[SUPV#]

FROM
    (FITSCHEDULED INNER JOIN SATELLITE2 ON FITSCHEDULED.EMPID = SATELLITE2.[EMP ID])
    INNER JOIN SATPOSITION
        ON SATELLITE2.[POSITION#] = SATPOSITION.[POSITION#];
