SELECT
    VACCINE.EID,
    VACCINE.VACCINE,
    VACCINE.VACDATE,
Year([VACDATE]) AS [Year],
    VACCINE.OUTCOME

FROM
    VACCINE

WHERE
    (((VACCINE.VACCINE)="4") AND ((Year([VACDATE]))=Year(Now())));
