SELECT
    HANDWASHING.HWID,
    HANDWASHING.EID,
    HANDWASHING.AUDTYPE,
    HANDWASHING.HWDATE,
    HANDWASHING.DISCIPLINE,
    HANDWASHING.OPPOR,
    HANDWASHING.SHIFT,
    HANDWASHING.STEP1,
    HANDWASHING.STEP2,
    HANDWASHING.STEP3,
    HANDWASHING.STEP4,
    HANDWASHING.STEP5,
    HANDWASHING.NOTES,
    UNIT.UNITSUB,
    UNIT.UNITMAIN,
    HANDWASHING.DELETE,
    [STEP1]+[STEP2]+[STEP3]+[STEP4]+[STEP5] AS [Decimal],
    Format(
        [Decimal],
        "Percent"
    )AS [Percent Correct],
    BUILDING.[BUILDING#]

FROM
    (UNIT INNER JOIN HANDWASHING ON UNIT.UNITSUB = HANDWASHING.UNIT)
    INNER JOIN BUILDING
        ON UNIT.BUI = BUILDING.BUI

WHERE
    (((HANDWASHING.DELETE) Is Null));
