SELECT
    VACCINE.EID,
    VACCINES.VACKEY,
Max(VACCINE.VACDATE) AS MaxOfVACDATE

FROM
    VACCINE
    LEFT JOIN VACCINES
        ON VACCINE.VACCINE = VACCINES.VACKEY

GROUP BY
    VACCINE.EID
    VACCINES.VACKEY

HAVING
    (((VACCINES.VACKEY)="9"));
