SELECT
    VACCINE.VCID,
    DEQRESOLUTION.DEQKEY,
    VACCINE.EMPPAT,
    VACCINE.EID,
    VACCINE.VACCINE,
    VACCINE.OUTCOME,
    VACCINE.SHIFT,
    VACCINE.UNIT,
    VACCINE.BLDG,
    VACCINE.VACDATE,
    VACCINE.NOTES,
    VACCINE.Alias,
    VACCINE.Timestamp,
    VACCINE.VACSUB,
    VACCINE.DISCIPLIN,
    VACCINES.VACDESC,
    VACCINESUB.VACSUBDESC,
    SATELLITE2.JOBTITLE,
    SATELLITE2.[BLDG#],
    SATELLITE2.POD,
    SATELLITE2.WARD

FROM
    (((VACCINE LEFT JOIN DEQRESOLUTION ON VACCINE.VCKEY = DEQRESOLUTION.DEQKEY) LEFT JOIN VACCINES ON VACCINE.VACCINE = VACCINES.VACKEY) LEFT JOIN VACCINESUB ON VACCINE.VACSUB = VACCINESUB.VACSUBKEY)
    LEFT JOIN SATELLITE2
        ON VACCINE.EID = SATELLITE2.[EMP ID]

WHERE
    (((DEQRESOLUTION.DEQKEY) Is Null));
