SELECT
    VACCINE.EMPPAT,
    VACCINE.EID,
    VACCINE.OUTCOME,
    VACCINE.Alias,
    VACCINE.Timestamp,
    VACCINES.VACDESC,
    VACCINES.VACKEY,
    VACCINE.VACDATE

FROM
    INFECTvacc010MR
    INNER JOIN (VACCINE LEFT JOIN VACCINES
        ON VACCINE.VACCINE = VACCINES.VACKEY) ON (INFECTvacc010MR.MaxOfVACDATE = VACCINE.VACDATE)
        AND
        (INFECTvacc010MR.VACKEY = VACCINE.VACCINE)
        AND
        (INFECTvacc010MR.EID = VACCINE.EID)

WHERE
    (((VACCINES.VACKEY)="10"));
