SELECT
    BG.STATUS,
    INSPMAIN.INSP_DESC,
    INSPECTIONS.INSP_NM,
    INSPECTIONS.INSP_TP,
    BG.DATECOMP,
    BG.NEXTDATE

FROM
    INSPMAIN
    INNER JOIN (INSPECTIONS INNER JOIN BG
        ON INSPECTIONS.ID = BG.INSPDESC) ON INSPMAIN.INSP_TYPE = BG.INSPTYPE

WHERE
    (((BG.STATUS)="Pending" Or (BG.STATUS)="Not Completed"));
