SELECT
    tbl1Employees.EMPID,
    DIGITALSIGNATURES.Alias,
    DIGITALSIGNATURES.DefaultSig,
    DIGITALSIGNATURES.FilePath,
    DIGITALSIGNATURES.TimeStamp

FROM
    DIGITALSIGNATURES
    RIGHT JOIN tbl1Employees
        ON DIGITALSIGNATURES.EMPID = tbl1Employees.EMPID;
