SELECT
    CODES.CNAME,
    CEVENTS.CTIME,
    CEVENTS.CDate,
    BUILDING.[BUILDING#],
    UNIT.UNITSUB,
    UNIT.UNITMAIN,
    CEVENTS.NOTES,
    SHIFT.CSHIFT

FROM
    (BUILDING RIGHT JOIN (CODES RIGHT JOIN (UNIT RIGHT JOIN CEVENTS ON UNIT.UNITSUB = CEVENTS.CUNIT) ON CODES.CDID = CEVENTS.CTYPE) ON BUILDING.BUI = CEVENTS.CBUILD)
    INNER JOIN SHIFT
        ON CEVENTS.CTIME = SHIFT.CTIME;
