SELECT
    NEARMISS.EMPID,
    NEARMISS.NMDATETM,
    NEARMISS.SEVERITY,
    NEARMISS.OCCUR,
    UNIT.UNITSUB,
    UNIT.UNITMAIN,
    BUILDING.[BUILDING#],
    NEARMISS.COMMENT

FROM
    NEARMISS
    INNER JOIN (UNIT INNER JOIN BUILDING
        ON UNIT.BUI = BUILDING.BUI) ON NEARMISS.UNIT = UNIT.UNITSUB

WHERE
    (((NEARMISS.NMDATETM) Between [Forms]![NearMissReports]![SDATE1] And [Forms]![NearMissReports]![SDATE3]));
