SELECT
    NEARMISS.EMPID,
    NEARMISS.NMDATETM,
    NEARMISS.SEVERITY,
    NEARMISS.OCCUR,
    UNIT.UNITSUB,
    UNIT.UNITMAIN,
    BUILDING.[BUILDING#],
    NEARMISS.COMMENT,
    NEARMISSRES.NMID,
    NEARMISSRES.RESOLUTION,
    IIf(
IsNull([NEARMISSRES].[NMID]),
        "Outstanding",
        "Resolved"
    )AS Status,
    NEARMISS.NMID,
    NEARMISS.NMKEY

FROM
    NEARMISSRES
    RIGHT JOIN (NEARMISS LEFT JOIN (UNIT LEFT JOIN BUILDING
        ON UNIT.BUI = BUILDING.BUI) ON NEARMISS.UNIT = UNIT.UNITSUB) ON NEARMISSRES.NMID = NEARMISS.NMID;
