SELECT
    SATELLITE2.[EMP ID],
    SATELLITE2.[POSITION#],
    SATELLITE2.JOBTITLE,
    SATELLITE2.[BLDG#],
    SATELLITE2.POD,
    SATELLITE2.WARD,
    SATELLITE2.[Gender Desc],
    SATELLITE2.[RACE DESCRIPT],
    SATELLITE2.[CC-BASE],
    SATELLITE2.[CC-DESC],
    SATELLITE2.[POSTYP DESC],
    SATELLITE2.ZIPCODE,
    SATELLITE2.Location,
    SATELLITE2.[Shift Desc],
    SATELLITE2.Payband_ID,
    SATELLITE2.[Full Name],
    SATELLITE2.FIRSTNAME,
    SATELLITE2.MI,
    SATELLITE2.NursingDesignationCode,
    SATELLITE2.[ESH-HIRE-DATE],
    SATELLITE2.[POS-START-DATE],
    SATELLITE2.SEPARATION,
    SATELLITE2.[EXIT-REASON],
    SATELLITE2.EMPSTATUS,
    [BLDG#] & " - " & [POD] & " - " & [WARD] AS [BUI-UNIT],
    [BLDG#] & " - " & [POD] & " - " & [WARD] & " - " & [CC-DESC] AS [BUI-UNIT-CC]

FROM
    SATELLITE2

WHERE
    (((SATELLITE2.[EMP ID])<>"000000000"));
