SELECT
    SATELLITE2.[EMP ID],
    SATELLITE2.[POSITION#],
    SATELLITE2.JOBTITLE,
    SATELLITE2.[BLDG#],
    SATELLITE2.POD,
    SATELLITE2.WARD,
    SATELLITE2.[Gender Desc],
    SATELLITE2.[RACE DESCRIPT],
    SATELLITE2.[CC-BASE],
    SATELLITE2.[CC-DESC],
    SATELLITE2.[POSTYP DESC],
    SATELLITE2.ZIPCODE,
    SATELLITE2.Location,
    SATELLITE2.[Shift Desc],
    SATELLITE2.Payband_ID,
    SATELLITE2.[Full Name],
    SATELLITE2.FIRSTNAME,
    SATELLITE2.MI,
    SATELLITE2.NursingDesignationCode,
    SATELLITE2.[ESH-HIRE-DATE],
    SATELLITE2.[POS-START-DATE],
    SATELLITE2.SEPARATION,
    SATELLITE2.[EXIT-REASON],
    N95APPRV.N95APPRV,
    N95APPRV.MEDSCREEN,
    N95APPRV.N95DATE

FROM
    N95APPRV
    LEFT JOIN SATELLITE2
        ON N95APPRV.EMPID = SATELLITE2.[EMP ID]

WHERE
    (((N95APPRV.N95APPRV)="yes") AND ((N95APPRV.MEDSCREEN)="yes"));
