SELECT
Max(SDTCOURSECOMP.[Last Launch]) AS [MaxOfLast Launch],
    SDTCOURSECOMP.[User ID],
    SDTCOURSECOMP.COURSEID,
    SDTCOURSECOMP.YearComp

FROM
    SDTCOURSECOMP

GROUP BY
    SDTCOURSECOMP.[User ID]
    SDTCOURSECOMP.COURSEID
    SDTCOURSECOMP.YearComp

HAVING
    (((SDTCOURSECOMP.COURSEID)<>"0000" And (SDTCOURSECOMP.COURSEID) Is Not Null))

ORDER BY
    SDTCOURSECOMP.[User ID]
    SDTCOURSECOMP.COURSEID
    SDTCOURSECOMP.YearComp;
