SELECT
    CSC.EMPID,
    SATELLITE2.[Full Name],
    SATELLITE2.JOBTITLE,
    CSCCODES.CSCDESC,
    CSC.SHIFT,
    BUILDING.[BUILDING#],
    UNIT.UNITMAIN,
    UNIT.UNITSUB,
    CSC.SDATE,
    NONVSN.DESC,
    DEQRESOLUTION.DEQKEY

FROM
    (((UNIT INNER JOIN (BUILDING INNER JOIN (CSCCODES INNER JOIN CSC ON CSCCODES.CODEID = CSC.SUBTYPEID) ON BUILDING.BUI = CSC.BLDG) ON UNIT.UNITSUB = CSC.UNIT) INNER JOIN SATELLITE2 ON CSC.EMPID = SATELLITE2.[EMP ID]) LEFT JOIN NONVSN ON SATELLITE2.NursingDesignationCode = NONVSN.NDCID)
    LEFT JOIN DEQRESOLUTION
        ON CSC.CSCKEY = DEQRESOLUTION.DEQKEY

WHERE
    (((CSCCODES.CSCDESC) Like "*" & Forms!StaffingReports!EVENT & "*") And ((CSC.SDATE) Like "*" & Forms!StaffingReports!SDATE2 & "*") And ((DEQRESOLUTION.DEQKEY) Is Null))

ORDER BY
    CSC.SDATE DESC;
