SELECT
    CSC.EMPID,
    CSCCODES.CSCDESC,
    CSC.SHIFT,
    BUILDING.[BUILDING#],
    UNIT.UNITMAIN,
    UNIT.UNITSUB,
    CSC.STIME,
    CSC.SDATE,
    CSC.NOTES,
    CSC.REFATT,
    CSC.SUBTYPEID,
    CSC.DELETE,
    CSC.TYPEID,
    CSC.THOURS,
    CSC.CSCKEY,
    EmployeeOnlyALL.[Full Name],
    DEQRESOLUTION.DEQKEY

FROM
    ((((CSC LEFT JOIN EmployeeOnlyALL ON CSC.EMPID = EmployeeOnlyALL.[EMP ID]) LEFT JOIN DEQRESOLUTION ON CSC.CSCKEY = DEQRESOLUTION.DEQKEY) LEFT JOIN CSCCODES ON CSC.SUBTYPEID = CSCCODES.CODEID) LEFT JOIN UNIT ON CSC.UNIT = UNIT.UNITSUB)
    LEFT JOIN BUILDING
        ON CSC.BLDG = BUILDING.BUI

WHERE
    (((CSC.DELETE) Is Null) AND ((DEQRESOLUTION.DEQKEY) Is Null));
