SELECT
    SATELLITE2.[Full Name],
    CSC.EMPID,
    SATELLITE2.JOBTITLE,
    CSCCODES.CSCDESC,
    CSC.THOURS,
    CSC.SHIFT,
    BUILDING.[BUILDING#],
    UNIT.UNITMAIN,
    UNIT.UNITSUB,
    CSC.SDATE,
    CSC.NOTES,
    CSC.DELETE,
    NONVSN.DESC

FROM
    (((UNIT INNER JOIN (BUILDING INNER JOIN (CSCCODES INNER JOIN CSC ON CSCCODES.CODEID = CSC.SUBTYPEID) ON BUILDING.BUI = CSC.BLDG) ON UNIT.UNITSUB = CSC.UNIT) INNER JOIN SATELLITE2 ON CSC.EMPID = SATELLITE2.[EMP ID]) LEFT JOIN NONVSN ON SATELLITE2.NursingDesignationCode = NONVSN.NDCID)
    LEFT JOIN DEQRESOLUTION
        ON CSC.CSCKEY = DEQRESOLUTION.DEQKEY

WHERE
    (((CSC.SDATE) Like "*" & Forms!StaffingReports!SDATE & "*") And ((CSC.DELETE) Is Null) And ((DEQRESOLUTION.DEQKEY) Is Null))

ORDER BY
    CSC.SDATE DESC;
