SELECT
    SATELLITE2.[Full Name],
    CSC.EMPID,
    CSCCODES.CSCDESC,
    CSC.THOURS,
    CSC.SHIFT,
    BUILDING.[BUILDING#],
    UNIT.UNITMAIN,
    UNIT.UNITSUB,
    CSC.SDATE,
    NONVSN.DESC,
    SATELLITE2.JOBTITLE,
    CSC.DELETE,
    CSC.REFATT,
    DEQRESOLUTION.DEQKEY

FROM
    (((((CSC INNER JOIN CSCCODES ON CSC.SUBTYPEID = CSCCODES.CODEID) INNER JOIN BUILDING ON CSC.BLDG = BUILDING.BUI) INNER JOIN UNIT ON CSC.UNIT = UNIT.UNITSUB) LEFT JOIN SATELLITE2 ON CSC.EMPID = SATELLITE2.[EMP ID]) LEFT JOIN NONVSN ON SATELLITE2.NursingDesignationCode = NONVSN.NDCID)
    LEFT JOIN DEQRESOLUTION
        ON CSC.CSCKEY = DEQRESOLUTION.DEQKEY

WHERE
    (((CSCCODES.CSCDESC)="Mandatory Shift" Or (CSCCODES.CSCDESC)="Voluntary Shift") AND ((CSC.SDATE) Between [Forms]![StaffingReports]![SDATE4] And [Forms]![StaffingReports]![SDATE5]) AND ((CSC.DELETE) Is Null) AND ((CSC.REFATT)<>"Refused" And (CSC.REFATT)<>"Canceled" And (CSC.REFATT)<>"NCNS") AND ((DEQRESOLUTION.DEQKEY) Is Null));
