SELECT
    STAYINT.EMPID,
    STAYINT.SDATE

FROM
    STAYINT
    LEFT JOIN DEQRESOLUTION
        ON STAYINT.SIKEY = DEQRESOLUTION.DEQKEY

GROUP BY
    STAYINT.EMPID
    STAYINT.SDATE
    DEQRESOLUTION.DEQKEY

HAVING
    (((DEQRESOLUTION.DEQKEY) Is Null));
