SELECT
    AFFILIATIONPOC.POCID,
    AFFILIATIONPROGRAM.AGREENUM,
    AFFILIATIONPROGRAM.SCHID,
    AFFILIATIONPOC.POCFNAME,
    AFFILIATIONPOC.POCLNAME,
    AFFILIATIONPOC.POCPHONE,
    AFFILIATIONPOC.POCEMAIL,
    AFFILIATIONPOC.POCSTATUS

FROM
    AFFILIATIONPROGRAM
    RIGHT JOIN (AFFILIATIONPOC INNER JOIN AFFPLINK
        ON AFFILIATIONPOC.POCID = AFFPLINK.POCID) ON AFFILIATIONPROGRAM.[AGREENUM] = AFFPLINK.AGREENUM

WHERE
    (((AFFILIATIONPROGRAM.AGREENUM)=[Forms]![StudentSchools]![AGREECOMBO]));
