SELECT
    AFFILIATIONPROGRAM.AGREENUM,
    AFFILIATIONPROGRAM.SCHID,
    AFFILIATIONPROGRAM.PROGNAME,
    AFFILIATIONPROGRAM.PROGSTATUS,
    AFFILIATIONPROGRAM.INTIATIONDT,
    AFFILIATIONPROGRAM.EXPIRDT

FROM
    AFFILIATIONPROGRAM;
