SELECT
    AFFILIATIONPROGRAM.INTIATIONDT,
    AFFILIATIONPROGRAM.AGREENUM,
    AFFILIATIONSCHOOL.SCHNAME,
    AFFILIATIONPROGRAM.PROGNAME,
    AFFILIATIONPROGRAM.PROGSTATUS

FROM
    AFFILIATIONPROGRAM
    INNER JOIN AFFILIATIONSCHOOL
        ON AFFILIATIONPROGRAM.[SCHID] = AFFILIATIONSCHOOL.[SCHID]

WHERE
    (((AFFILIATIONPROGRAM.PROGSTATUS)="ACTIVE"));
