SELECT
    AFFILIATIONPROGRAM.AGREENUM,
    AFFILIATIONPROGRAM.PROGNAME,
    AFFILIATIONSCHOOL.SCHNAME,
    AFFILIATIONPROGRAM.INTIATIONDT,
    AFFILIATIONPROGRAM.EXPIRDT

FROM
    AFFILIATIONPROGRAM
    INNER JOIN AFFILIATIONSCHOOL
        ON AFFILIATIONPROGRAM.[SCHID] = AFFILIATIONSCHOOL.[SCHID];
