SELECT
    SupervisorPOSNumbers.[SUPV#],
    SATELLITE2.[EMP ID],
    SATELLITE2.[Full Name],
    SATELLITE2.JOBTITLE,
    SATELLITE2.[BLDG#],
    SATELLITE2.POD,
    SATELLITE2.WARD,
    SATELLITE2.[CC-BASE],
    SATELLITE2.[CC-DESC],
    SATELLITE2.EMPSTATUS

FROM
    SATELLITE2
    RIGHT JOIN SupervisorPOSNumbers
        ON SATELLITE2.[POSITION#] = SupervisorPOSNumbers.[SUPV#]

WHERE
    (((SATELLITE2.EMPSTATUS)="current" Or (SATELLITE2.EMPSTATUS)="Place Holder"));
