SELECT
    SATELLITE2.[SUPV#],
    SATELLITE2.EMPSTATUS

FROM
    SATELLITE2

GROUP BY
    SATELLITE2.[SUPV#]
    SATELLITE2.EMPSTATUS

HAVING
    (((SATELLITE2.[SUPV#]) Is Not Null) AND ((SATELLITE2.EMPSTATUS)="Current"));
