SELECT
    EMPSERVICE.[EMP ID],
    SATTEMPKEY.SSN,
    EMPSERVICE.[POS-START-DATE] AS [STEP2-POS-START-DATE],
    EMPSERVICE.[EXIT-DATE] AS [STEP1-EXIT-DATE],
    [SequentialKey]+1 AS SequentialKeyNum,
    EMPSERVICE.ESERVID

FROM
    EMPSERVICE
    INNER JOIN SATTEMPKEY
        ON EMPSERVICE.[EMP ID] = SATTEMPKEY.[EMP ID];
