SELECT
    ERROLECODE.[ROLE-CODE],
Max(SDTCOURSEYEAR.SDTYEAR) AS MaxOfSDTYEAR

FROM
    ERROLECODE
    INNER JOIN SDTCOURSEYEAR
        ON ERROLECODE.[ROLE-CODE] = SDTCOURSEYEAR.[ROLE-CODE]

GROUP BY
    ERROLECODE.[ROLE-CODE];
