SELECT
    SDTCOURSEYEAR.SDTDATEYEAR,
    SDTCOURSEYEAR.SDTYEAR,
    SDTREQUIREMENTS.[ROLE-CODE],
    SDTCOURSE.COURSEID,
    SDTCOURSE.COURSENAME,
    SDTREQUIREMENTS.REQUIRED,
    SDTCOURSE.COURSEESTABLISH,
    SDTOCCUR.OCCURDESC,
    SDTOCCUR.OCCURPERIOD,
    SDTCOURSETYPE.COURSEDESC,
    SDTCLASSTYPE.CLASSTYDESC,
    SDTTRNGTYPE.TRNTYPDESC,
    SDTTRNGCAT.TRNCATDESC,
    SDTTRNGCAT.TRNCATID2,
    IIf(
        [OCCURDESC]="Annual",
        [SDTDATEYEAR]+364,
        [SDTDATEYEAR]+90
    )AS DUEDATE

FROM
    (((((SDTCOURSEYEAR INNER JOIN (SDTCOURSE INNER JOIN SDTREQUIREMENTS ON SDTCOURSE.COURSEID = SDTREQUIREMENTS.COURSEID) ON SDTCOURSEYEAR.[ROLE-CODE] = SDTREQUIREMENTS.[ROLE-CODE]) LEFT JOIN SDTOCCUR ON SDTCOURSE.OCCURID = SDTOCCUR.OKEY) LEFT JOIN SDTCLASSTYPE ON SDTCOURSE.CLASSTYID = SDTCLASSTYPE.CLASSTYKEY) LEFT JOIN SDTTRNGTYPE ON SDTCOURSE.TRNTYPID = SDTTRNGTYPE.TRNTYPID) LEFT JOIN SDTTRNGCAT ON SDTCOURSE.TRNCATID = SDTTRNGCAT.TRNCATID)
    LEFT JOIN SDTCOURSETYPE
        ON SDTCOURSE.COURSETYPE = SDTCOURSETYPE.CKEY

WHERE
    (((SDTREQUIREMENTS.REQUIRED)=Yes))

ORDER BY
    SDTCOURSEYEAR.SDTYEAR
    SDTREQUIREMENTS.[ROLE-CODE]
    SDTCOURSE.COURSEID;
