SELECT
    SDTCOURSE.COURSEID,
    SDTCOURSE.COURSENAME,
    SDTCOURSE.COURSEESTABLISH,
    SDTREQUIREMENTS.[ROLE-CODE],
    SDTREQUIREMENTS.REQUIRED,
    SDTCLASSTYPE.CLASSTYDESC,
    SDTCOURSETYPE.COURSEDESC,
    SDTOCCUR.OCCURDESC,
    SDTOCCUR.OCCURPERIOD,
    SDTTRNGTYPE.TRNTYPDESC,
    SDTTRNGCAT.TRNCATDESC,
    SDTTRNGCAT.TRNCATID2,
    SDTOCCUR.OKEY,
    SDTCOURSEYEAR.SDTYEAR,
    SDTCOURSEYEAR.SDTDATEYEAR,
    DateSerial(
        [SDTYEAR],
Month([COURSEESTABLISH]),
Day([SDTDATEYEAR])
    )AS INTDATEASSIGN

FROM
    SDTCOURSEYEAR
    INNER JOIN ((((((SDTCOURSE INNER JOIN SDTREQUIREMENTS
        ON SDTCOURSE.COURSEID = SDTREQUIREMENTS.COURSEID) INNER JOIN SDTCLASSTYPE ON SDTCOURSE.CLASSTYID = SDTCLASSTYPE.CLASSTYKEY) INNER JOIN SDTCOURSETYPE ON SDTCOURSE.COURSETYPE = SDTCOURSETYPE.CKEY) INNER JOIN SDTOCCUR ON SDTCOURSE.OCCURID = SDTOCCUR.OKEY) INNER JOIN SDTTRNGTYPE ON SDTCOURSE.TRNTYPID = SDTTRNGTYPE.TRNTYPID) INNER JOIN SDTTRNGCAT ON SDTCOURSE.TRNCATID = SDTTRNGCAT.TRNCATID) ON SDTCOURSEYEAR.[ROLE-CODE] = SDTREQUIREMENTS.[ROLE-CODE]

WHERE
    (((SDTCOURSE.COURSEID) Is Not Null) AND ((SDTCOURSE.COURSENAME) Is Not Null) AND ((SDTCOURSE.COURSEESTABLISH) Is Not Null) AND ((SDTREQUIREMENTS.[ROLE-CODE]) Is Not Null) AND ((SDTREQUIREMENTS.REQUIRED)=True) AND ((SDTCLASSTYPE.CLASSTYDESC) Is Not Null) AND ((SDTCOURSETYPE.COURSEDESC) Is Not Null) AND ((SDTOCCUR.OCCURDESC) Is Not Null) AND ((SDTOCCUR.OCCURPERIOD) Is Not Null) AND ((SDTTRNGTYPE.TRNTYPDESC) Is Not Null) AND ((SDTTRNGCAT.TRNCATDESC) Is Not Null) AND ((SDTTRNGCAT.TRNCATID2) Is Not Null) AND ((SDTOCCUR.OKEY) Is Not Null) AND ((SDTCOURSEYEAR.SDTYEAR) Is Not Null) AND ((SDTCOURSEYEAR.SDTDATEYEAR) Is Not Null));
