SELECT
    SDTQTRYR.*,
    SDTQUARTERS.QDAYASSIGN,
    SDTQUARTERS.QMONTHASSIGN,
    SDTQUARTERS.QDAYDUE,
    SDTQUARTERS.QMONTHDUE

FROM
    SDTQTRYR
    INNER JOIN SDTQUARTERS
        ON SDTQTRYR.QTRID = SDTQUARTERS.QTRID;
