SELECT
    SDTGLAIT.EMPID,
    SDTGLAIT.GLAIT,
    SATELLITE2.[EMP ID],
    SATELLITE2.[Full Name],
    SATELLITE2.EMPSTATUS,
    SATELLITE2.JOBTITLE,
    SATELLITE2.[POS-START-DATE],
    SATELLITE2.[BLDG#],
    SATELLITE2.POD,
    SATELLITE2.WARD

FROM
    SATELLITE2
    LEFT JOIN SDTGLAIT
        ON SATELLITE2.[EMP ID] = SDTGLAIT.EMPID

WHERE
    (((SDTGLAIT.GLAIT) Is Null) AND ((SATELLITE2.[EMP ID]) Is Not Null) AND ((SATELLITE2.EMPSTATUS)="Current"));
