SELECT
    SDTCOURSECOMP.[Content Title],
    SDTCOURSECOMP.[Content Type],
    SDTCOURSECOMP.COURSEID

FROM
    SDTCOURSECOMP

WHERE
    (((SDTCOURSECOMP.COURSEID)="0000") AND ((SDTCOURSECOMP.[Content Type])<>"Curriculum"))

GROUP BY
    SDTCOURSECOMP.[Content Title]
    SDTCOURSECOMP.[Content Type] PIVOT SDTCOURSECOMP.COURSEID;
