SELECT
    SATTEMPKEY.SSN,
Min(EMPSERVICE.[ESH-HIRE-DATE]) AS [MinOfESH-HIRE-DATE]

FROM
    EMPSERVICE
    INNER JOIN SATTEMPKEY
        ON EMPSERVICE.[EMP ID] = SATTEMPKEY.[EMP ID]

GROUP BY
    SATTEMPKEY.SSN;
