SELECT
    SDTASSIGNCLASS.COURSEID,
    SDTASSIGNCLASS.DATEASSIGN,
    SDTASSIGNCLASS.DATEDUE,
    SDTASSIGNCLASS.ASSIGNID,
    IIf(
Date()<[DATEDUE],
        "Current",
        "Ended"
    )AS Status

FROM
    SDTASSIGNCLASS
    INNER JOIN SDTCOURSE
        ON SDTASSIGNCLASS.COURSEID = SDTCOURSE.COURSEID;
