SELECT
    SDTCOURSE.COURSEID,
    SDTCOURSE.COURSENAME,
    SDTCOURSETYPE.COURSEDESC,
    SDTTRNGCAT.TRNCATDESC,
    SDTTRNGTYPE.TRNTYPDESC,
    SDTCOURSE.COURSEESTABLISH,
    SDTCLASSTYPE.CLASSTYDESC,
    SDTTRNGCAT.TRNCATID2,
    DEQRESOLUTION.DEQKEY

FROM
    ((((SDTCOURSE LEFT JOIN SDTCOURSETYPE ON SDTCOURSE.COURSETYPE = SDTCOURSETYPE.CKEY) LEFT JOIN SDTTRNGCAT ON SDTCOURSE.TRNCATID = SDTTRNGCAT.TRNCATID) LEFT JOIN SDTTRNGTYPE ON SDTCOURSE.TRNTYPID = SDTTRNGTYPE.TRNTYPID) LEFT JOIN SDTCLASSTYPE ON SDTCOURSE.CLASSTYID = SDTCLASSTYPE.CLASSTYKEY)
    LEFT JOIN DEQRESOLUTION
        ON SDTCOURSE.COURSEID = DEQRESOLUTION.DEQKEY

WHERE
    (((DEQRESOLUTION.DEQKEY) Is Null))

ORDER BY
    SDTCOURSE.COURSEID;
