SELECT
First(SDTCOURSECOMP.[User ID]) AS [User ID Field],
First(SDTCOURSECOMP.COURSEID) AS [COURSEID Field],
First(SDTCOURSECOMP.YearComp) AS [YearComp Field],
Count(SDTCOURSECOMP.[User ID]) AS NumberOfDups

FROM
    SDTCOURSECOMP

GROUP BY
    SDTCOURSECOMP.[User ID]
    SDTCOURSECOMP.COURSEID
    SDTCOURSECOMP.YearComp

HAVING
    (((First(SDTCOURSECOMP.COURSEID)) Is Not Null And (First(SDTCOURSECOMP.COURSEID))<>"0000") AND ((Count(SDTCOURSECOMP.[User ID]))>1) AND ((Count(SDTCOURSECOMP.YearComp))>1));
