SELECT
    SDTCOURSECOMP.COURSEID,
    SDTCOURSECOMP.[Content Title]

FROM
    SDTCOURSECOMP

GROUP BY
    SDTCOURSECOMP.COURSEID
    SDTCOURSECOMP.[Content Title]

HAVING
    (((SDTCOURSECOMP.COURSEID)<>"0000" And (SDTCOURSECOMP.COURSEID) Is Not Null));
