SELECT
    SDTCOURSE.COURSEID,
    SDTCOURSE.COURSENAME,
    SDTCOURSE.IsSelected

FROM
    SDTCOURSE

WHERE
    (((SDTCOURSE.IsSelected)=Yes) AND ((SDTCOURSE.TRNCATID)="3" Or (SDTCOURSE.TRNCATID)="4"));
