SELECT
    SDTCOURSE.COURSEID,
    SDTCOURSE.COURSENAME,
    SDTCOURSE.IsSelected,
DLookUp("DEQKEY","DEQRESOLUTION","DEQKEY = '" & [SDTCOURSE]![COURSEID] & "'") AS Expr1

FROM
    SDTCOURSE

WHERE
    (((DLookUp("DEQKEY","DEQRESOLUTION","DEQKEY = '" & [SDTCOURSE]![COURSEID] & "'")) Is Null) AND ((SDTCOURSE.TRNCATID)="3" Or (SDTCOURSE.TRNCATID)="7" Or (SDTCOURSE.TRNCATID)="8" Or (SDTCOURSE.TRNCATID)="9" Or (SDTCOURSE.TRNCATID)="10"))

ORDER BY
    SDTCOURSE.COURSEID;
