SELECT
    SDTREQUIREMENTS.[ROLE-CODE],
    SDTREQUIREMENTS.COURSEID,
    SDTREQUIREMENTS.REQUIRED,
    ERROLECODE.[ROLE-DESC],
    SDTCOURSE.OCCURID,
    SDTCOURSE.TRNTYPID,
    SDTCOURSE.TRNCATID,
    SDTCOURSE.COURSETYPE,
    SDTCOURSE.COURSEESTABLISH

FROM
    SDTCOURSE
    INNER JOIN (SDTREQUIREMENTS INNER JOIN ERROLECODE
        ON SDTREQUIREMENTS.[ROLE-CODE] = ERROLECODE.[ROLE-CODE]) ON SDTCOURSE.COURSEID = SDTREQUIREMENTS.COURSEID

ORDER BY
    SDTREQUIREMENTS.[ROLE-CODE];
