SELECT
    SDTCOURSECOMP.[User ID],
    SDTCOURSECOMP.COURSEID,
    SDTCOURSECOMP.YearComp,
Min(SDTCOURSECOMP.[Last Launch]) AS [MinOfLast Launch]

FROM
    SDTCOURSECOMP

GROUP BY
    SDTCOURSECOMP.[User ID]
    SDTCOURSECOMP.COURSEID
    SDTCOURSECOMP.YearComp

HAVING
    (((SDTCOURSECOMP.COURSEID) Is Not Null));
