SELECT
    SDTCOURSE.*,
    DEQRESOLUTION.DEQKEY

FROM
    SDTCOURSE
    LEFT JOIN DEQRESOLUTION
        ON SDTCOURSE.COURSEID = DEQRESOLUTION.DEQKEY

WHERE
    (((DEQRESOLUTION.DEQKEY) Is Null));
