SELECT
    SERVICEBREAK.EMPID,
    SERVICEBREAK.[POSITION#],
    SERVICEBREAK.[POS-START-DATE] AS [SERBRK POS-START-DATE],
    SERVICEBREAK.[ESH-START-DATE] AS [SERBRK ESH-START-DATE],
    SERVICEBREAK.[EXIT-DATE],
    SERVICEBREAK.[POS-RESTART-DATE]

FROM
    SERVICEBREAK;
