SELECT
    SDTCOURSE.COURSEID,
    SDTCOURSE.COURSEIDNUM,
    SDTCOURSE.COURSENAME,
    SDTTRNGCAT.TRNCATID2,
    SDTTRNGCAT.TRNCATDESC,
    SDTCOURSETYPE.COURSEDESC,
    SDTCLASSTYPE.CLASSTYDESC,
    SDTTRNGTYPE.TRNTYPDESC,
    SDTOCCUR.OCCURDESC,
    SDTOCCUR.OCCURPERIOD,
    SDTCOURSE.OCCURID,
    IIf(
IsNull([DEQKEY]),
        "Current",
        "Deleted"
    )AS Status,
    SDTCOURSE.Timestamp

FROM
    (((((SDTCOURSE LEFT JOIN SDTTRNGCAT ON SDTCOURSE.TRNCATID = SDTTRNGCAT.TRNCATID) LEFT JOIN SDTCOURSETYPE ON SDTCOURSE.COURSETYPE = SDTCOURSETYPE.CKEY) LEFT JOIN SDTCLASSTYPE ON SDTCOURSE.CLASSTYID = SDTCLASSTYPE.CLASSTYKEY) LEFT JOIN SDTTRNGTYPE ON SDTCOURSE.TRNTYPID = SDTTRNGTYPE.TRNTYPID) LEFT JOIN SDTOCCUR ON SDTCOURSE.OCCURID = SDTOCCUR.OKEY)
    LEFT JOIN DEQRESOLUTION
        ON SDTCOURSE.COURSEID = DEQRESOLUTION.DEQKEY

WHERE
    ((( IIf(
IsNull([DEQKEY]),
        "Current",
        "Deleted"
    ) )="Current"));
