SELECT
    SDTREQUIREMENTS.[ROLE-CODE],
    SDTREQUIREMENTS.COURSEID,
    SDTREQUIREMENTS.REQUIRED,
    ERROLECODE.[ROLE-DESC]

FROM
    SDTREQUIREMENTS
    INNER JOIN ERROLECODE
        ON SDTREQUIREMENTS.[ROLE-CODE] = ERROLECODE.[ROLE-CODE]

ORDER BY
    SDTREQUIREMENTS.[ROLE-CODE];
