SELECT
    UTILIZATION.UTILID,
    UTILIZATION.PatientID,
    UTILIZATION.Episode,
    [UtilDate]+[UtilTime] AS [DateTime],
    UTILIZATION.DMID,
    UTILIZATION.DEQID,
    DEQSUBCATS.SUBDEQNAME,
    DEQSUBCATS.WITHIN,
    [PatientID] & "-" & [Episode] AS patepi

FROM
    UTILIZATION
    INNER JOIN DEQSUBCATS
        ON UTILIZATION.DEQID = DEQSUBCATS.DEQKEY;
