SELECT
    UTILIZINT.INTID,
    UTILIZINT.PatientID AS PID,
    UTILIZINT.Episode,
    UTILIZINT.Alias,
    UTILIZINT.[Time Stamp],
    UTILIZINT.BUI,
    UTILIZINT.UNIT

FROM
    UTILIZINT;
